import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata1 = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const metadata = {
  title: "Login Page",
  description: "User login page for Next.js app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
       
      >
        <header>this is header</header>
        {children}
      </body>
    </html>
  );
}
